---
common_timezone: Europe/Paris
common_locale: fr_FR.UTF-8
common_swap_size_mb: 2048
common_swap_file: /var/swap
common_unattended_upgrades: true

ssh_port: 2222
ssh_allowed_users: [ansible]
ssh_password_authentication: false
ssh_permit_root_login: "no"
ssh_max_auth_tries: 3

ufw_default_input_policy: deny
ufw_default_output_policy: allow
ufw_allowed_ports: []

fail2ban_bantime: 1h
fail2ban_findtime: 10m
fail2ban_maxretry: 5

admin_users: []
