---
infisical_version: "0.41.83"
infisical_install_dir: /usr/local/bin
infisical_identity_dir: /etc/infisical
infisical_runtime_user: lumiris
infisical_api_url: https://eu.infisical.com
infisical_project_slug: lumiris
infisical_env: prod

vault_infisical_client_id: ""
vault_infisical_client_secret: ""
